language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
  - node_modules
script:
  - cd functions
  - npm install
  - npm run lint
  - npm run test
  - cd ..
deploy:
  provider: firebase
  token:
    secure: ''
  skip_cleanup: true